papers:
  font-path: "src/main/resources/fonts"
  resources-path: "src/main/resources/images"
  fonts:
    - name: "hei"
      file: "simhei.ttf"
    - name: "fang"
      file: "simfang.ttf"
    - name: "kai"
      file: "simkai.ttf"
    - name: "xbs"
      file: "fzxbsjw.ttf"
    - name: "li"
      file: "stliti.ttf"
  settings:
    weeklyReport:
      top-margin: 72
      bottom-margin: 55.84
      left-margin: 90.14
      right-margin: 64.35
      default-font:
        name: "fang"
        size: 16
    importantForecast:
      top-margin: 72
      bottom-margin: 55.84
      left-margin: 90.14
      right-margin: 64.35
      default-font:
        name: "fang"
        size: 16
    specialWeatherService:
      top-margin: 54.43
      bottom-margin: 54.84
      left-margin: 70.9
      right-margin: 70.9
      default-font:
        name: "fang"
        size: 16

